### ISSUE TITLE
Cannot run troubleshoot locally

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot.sh#465]
It seems the dependencies are too old. When trying to build the project, the tools expect `python2` to be installed in the system

The failing command is `make publish`

**Comment by xavpaice** [comment]
Could you add a bit more detail here as to what you mean?

**Comment by xavpaice** [comment]
On an M1 Mac, when I run `make deps` I get the following:

```
error /Users/xavpaice/work/troubleshoot.sh/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/xavpaice/work/troubleshoot.sh/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-arm64v8.tar.gz
ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@20.1.0 | darwin | arm64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/xavpaice/work/troubleshoot.sh/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/xavpaice/work/troubleshoot.sh/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/xavpaice/work/troubleshoot.sh/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/xavpaice/work/troubleshoot.sh/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/xavpaice/work/troubleshoot.sh/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/xavpaice/work/troubleshoot.sh/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/xavpaice/work/troubleshoot.sh/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:196:21)
gyp ERR! System Darwin 22.4.0
gyp ERR! command "/opt/homebrew/Cellar/node/20.1.0/bin/node" "/Users/xavpaice/work/troubleshoot.sh/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/xavpaice/work/troubleshoot.sh/node_modules/sharp

```

**Comment by banjoh** [comment]
I'm getting the same result as well. I tried to get past `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.` error by installing `python2` (a non-trivial exercise) but that did not work. I got way too many other issues with dependencies. I thought it not better go down that rabbit hole. Obviously this project gets built by netlify so we'd need to see how that works.

I raised this issue when trying to build the project in an effort to get a baseline to work from when attempting to upgrade dependencies. They are very old.

**Comment by DexterYan** [comment]
Updated the older node version to 20. Now it should be easy to setup local development. Here is the docs https://github.com/replicatedhq/troubleshoot.sh?tab=readme-ov-file#local-development
